source 'http://rubygems.org'

gem 'nanoc'
gem 'redcarpet'
gem 'rack'
gem 'mime-types'
gem 'ZURB-foundation'
gem 'haml'
gem 'compass'
gem 'uglifier'
gem 'therubyracer'
gem 'systemu'
gem 'ruby-oembed'
gem 'nokogiri'
